apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolith
  template:
    metadata:
      labels:
        app: monolith
    spec:
      containers:
        - name: monolith
          image: REPLACE_ACR_LOGIN_SERVER/monolith:latest
          ports:
            - containerPort: 8000
          env:
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: workshop-observability
                  key: appinsights-connection-string
---
apiVersion: v1
kind: Service
metadata:
  name: monolith
spec:
  type: LoadBalancer
  selector:
    app: monolith
  ports:
    - port: 80
      targetPort: 8000
